{{- if .Values.global.database.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.database.passwordSecretName | default "pg-postgresql" }}
type: Opaque
data:
  {{ .Values.global.database.passwordSecretKey | default "postgres-password" }}: {{ .Values.global.database.password | b64enc }}
{{- end }}
