{{- if .Values.global.redis.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.redis.passwordSecretName | default "redis" }}
type: Opaque
data:
  {{ .Values.global.redis.passwordSecretKey | default "redis-password" }}: {{ .Values.global.redis.password | b64enc }}
{{- end }}
