apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graphql.fullname" . }}-database-migration
  labels:
    {{- include "graphql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  template:
    spec:
      serviceAccountName: {{ include "graphql.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ coalesce .Values.global.app.imagesTag .Values.image.tag .Chart.AppVersion }}"
        command: ["yarn", "predeploy"]
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.database.passwordSecretName | default "pg-postgresql" }}
                key: {{ .Values.global.database.passwordSecretKey | default "postgres-password"}}
          - name: DATABASE_URL
            value: postgres://{{ .Values.global.database.user }}:$(DATABASE_PASSWORD)@{{ .Values.global.database.host }}:{{ .Values.global.database.port }}/{{ .Values.global.database.name }}
          - name: REDIS_SERVER_HOST
            value: "{{ .Values.global.redis.host }}"
          - name: REDIS_SERVER_PORT
            value: "{{ .Values.global.redis.port }}"
          - name: REDIS_SERVER_USER
            value: "{{ .Values.global.redis.username }}"
          - name: REDIS_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.redis.passwordSecretName | default "redis"}}
                key: {{ .Values.global.redis.passwordSecretKey | default "redis-password" }}
          - name: AFFINE_INDEXER_SEARCH_PROVIDER
            value: "{{ .Values.global.indexer.provider }}"
          - name: AFFINE_INDEXER_SEARCH_ENDPOINT
            value: "{{ .Values.global.indexer.endpoint }}"
          - name: AFFINE_INDEXER_SEARCH_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.indexer.indexerSecretName | default "indexer"}}
                key: {{ .Values.global.redis.indexerSecretKey | default "indexer-apiKey" }}
        resources:
          requests:
            cpu: '100m'
            memory: '200Mi'
      restartPolicy: Never
  backoffLimit: 1
