global:
  app:
    imagesTag: canary
    env: beta
    buildType: 'stable'
  ingress:
    enabled: false
    className: ''
    host: affine.pro
    tls: []
  secret:
    secretName: 'server-private-key'
    privateKey: ''
  database:
    user: 'postgres'
    url: 'pg-postgresql'
    port: '5432'
    name: 'affine'
    password: ''
    passwordSecretName: 'pg-postgresql'
    passwordSecretKey: 'postgres-password'
    gcloud:
      enabled: false
      # use for migration
      cloudSqlInternal: ''
      connectionName: ''
      serviceAccount: ''
      cloudProxyReplicas: 3
      proxyPort: '5432'
  redis:
    enabled: true
    host: 'redis-master'
    port: '6379'
    username: ''
    password: ''
    passwordSecretName: 'redis'
    passwordSecretKey: 'redis-password'
    database: 0
  objectStorage:
    r2:
      enabled: false
      secretName: r2
      accountId: ''
      accessKeyId: ''
      secretAccessKey: ''
  gke:
    enabled: false

graphql:
  service:
    type: ClusterIP
    port: 3000
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

sync:
  service:
    type: ClusterIP
    port: 3010
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

renderer:
  service:
    type: ClusterIP
    port: 3000
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

web:
  service:
    type: ClusterIP
    port: 8080
