global:
  app:
    imagesTag: stable # stable, canary, etc
  ingress:
    enabled: false
    className: ''
    host: affine.pro
    tls: []
  secret:
    secretName: 'server-private-key'
    privateKey: ''
  database:
    user: 'postgres'
    host: 'pg-postgresql'
    port: '5432'
    name: 'affine'
    password: ''
    passwordSecretName: 'pg-postgresql'
    passwordSecretKey: 'postgres-password'
  redis:
    enabled: true
    host: 'redis-master'
    port: '6379'
    username: ''
    password: ''
    passwordSecretName: 'redis'
    passwordSecretKey: 'redis-password'
    database: 0
  indexer:
    provider: ''
    endpoint: ''
    username: ''
    password: ''

graphql:
  service:
    type: ClusterIP
    port: 3010
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'
